version: "3.9"

services:

  backend:
    build: 
      context: ./Backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
  frontend2:
    build: ./Frontend1
    container_name: frontend2
    ports:
      - "3001:3000"
    depends_on:
      - backend
  backend2:
    build:
      context: ./Backend
    container_name: backend2
    ports:
      - "8001:8000"